#pragma config(Motor,  port2,           vxMotor,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		if(vexRT[Btn8U] ==1)
		{
			motor[port2] = 128;
		}
		else if(vexRT[Btn8R] ==1){
			motor[port2] = 96;
		}
		else if(vexRT[Btn8D] ==1){
			motor[port2] = 64;
		}
		else if(vexRT[Btn8L] ==1){
			motor[port2] = 32;
		}
		else
		{
			motor[port2] = 0;
		}
	}
}
/*gear ratio ideas(temp)
7->1
	 3->1

new
7->3|
	 3->1|
			3->1
/*
