#pragma config(Motor,  port1,           TankL,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           TankR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Pickup1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Pickup2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Shooter1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Shooter2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Shooter3,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Shooter4,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	
	int leftJoystick = vexRT[Ch3];
	int rightJoystick = vexRT[Ch2];
	int intakeOn = false;
	int intakeOnLast = false;
	bool intakeRunning = false;
	int shooterOn = false;
	int shooterOnLast = false;
	bool shooterRunning = false;
	clearTimer(T1);
	
	while(true){
		
		//tank drive
		if(leftJoystick > 10 || leftJoystick < -10 || rightJoystick > 10 || rightJoystick < -10){
			motor[port1] = leftJoystick;
			motor[port2] = rightJoystick;
		}else{
			motor[port1] = 0;
			motor[port2] = 0;
		}
		intakeOnLast = intakeOn;
		intakeOn = vexRT[Btn8D];
		//intake motors
		if(intakeOn == false && intakeOnLast == true){
			if(intakeRunning == true){
				motor[port3] = 0;
				motor[port4] = 0;
				intakeRunning = false;
			}
			else{
				motor[port3] = 128;
				motor[port4] = 128;
				intakeRunning = true;
			}	
		}
		//shooter
		shooterOnLast = shooterOn;
		shooterOn = vexRT[Btn7D];
		if(shooterOn == false && shooterOnLast == true){
			if(shooterRunning == true){
				//stop if button is pressed
				motor[port5] = 0;
				motor[port6] = 0;
				motor[port7] = 0;
				motor[port8] = 0;
				shooterRunning = false;
			}
			else{
				clearTimer(T1);
				motor[port5] = 128;
				motor[port6] = -128;
				motor[port7] = 128;
				motor[port8] = -128;
				shooterRunning = true;
				
			}
			
		}
		if(time1[T1] > 5000 && shooterRunning == true){
				motor[port5] = 0;
				motor[port6] = 0;
				motor[port7] = 0;
				motor[port8] = 0;
				shooterRunning = false;
				clearTimer(T1);
		}
	}
}
